import { Stock } from '@/types/stock';

export const twStocks: Stock[] = [
  { code: '2301', name: '光宝科技', englishName: 'LITE-ON TECH' },
  { code: '2303', name: '联华电子', englishName: 'UMC (United Microelectronics Corp.)' },
  { code: '2308', name: '台达电子', englishName: 'DELTA ELEC (Delta Electronics, Inc.)' },
  { code: '2313', name: '华通电脑', englishName: 'COMPEQ MANUFACTURING CO., LTD.' },
  { code: '2317', name: '鸿海精密', englishName: 'Hon Hai Precision Industry Co., Ltd.' },
  { code: '2324', name: '仁宝电脑', englishName: 'COMPAL ELEC (Compal Electronics, Inc.)' },
  { code: '2330', name: '台积电', englishName: 'Taiwan Semiconductor Manufacturing Co., Ltd.' },
  { code: '2345', name: '智邦科技', englishName: 'Accton Technology Corporation' },
  { code: '2353', name: '宏碁', englishName: 'ACER INC' },
  { code: '2356', name: '英业达', englishName: 'Inventec Corporation' },
  { code: '2357', name: '华硕电脑', englishName: 'ASUSTEK COMPUTER (ASUSTeK Computer Inc)' },
  { code: '2360', name: '致茂电子', englishName: 'CHROMA ATE' },
  { code: '2368', name: '金像电子', englishName: 'GOLD CIRCUIT ELECTRONICS LTD.' },
  { code: '2376', name: '技嘉科技', englishName: 'GIGABYTE TECH (Giga-Byte Technology Co., Ltd)' },
  { code: '2379', name: '瑞昱半导体', englishName: 'REALTEK SEMI (Realtek Semiconductor Corp.)' },
  { code: '2382', name: '广达电脑', englishName: 'Quanta Computer Inc.' },
  { code: '2383', name: '台光电子', englishName: 'ELITE MATERIAL CO., LTD.' },
  { code: '2408', name: '南亚科技', englishName: 'NANYA TECH (Nanya Technology Corporation)' },
  { code: '2409', name: '友达光电', englishName: 'AUO Corporation' },
  { code: '2449', name: '京元电子', englishName: 'KING YUAN ELEC (King Yuan Electronics Co., Ltd)' },
  { code: '2454', name: '联发科技', englishName: 'MediaTek Inc.' },
  { code: '3017', name: '奇鋐科技', englishName: 'Asia Vital Components Co., Ltd. (AURAS)' },
  { code: '3034', name: '联咏科技', englishName: 'NOVATEK (Novatek Microelectronics Corp.)' },
  { code: '3035', name: '智原科技', englishName: 'GLOBAL UNICHIP (Global Unichip Corp.)' },
  { code: '3037', name: '欣兴电子', englishName: 'Unimicron Technology Corp.' },
  { code: '3044', name: '健鼎科技', englishName: 'Tripod Technology Corporation' },
  { code: '3088', name: '艾讯', englishName: 'ASIA VITAL (Axiomtek Co., Ltd.)' },
  { code: '3231', name: '纬创资通', englishName: 'Wistron Corporation' },
  { code: '3324', name: '双鸿科技', englishName: 'Auras Technology Co., Ltd.' },
  { code: '3406', name: '玉晶光电', englishName: 'GENIUS ELEC (Genius Electronic Optical)' },
  { code: '3443', name: '创意电子', englishName: 'ALCHIP TECH (Alchip Technologies, Ltd.)' },
  { code: '3526', name: '万润科技', englishName: 'ALL RING TECH' },
  { code: '3533', name: '嘉泽端子', englishName: 'LOTES (Lotes Co., Ltd.)' },
  { code: '3653', name: '健策精密', englishName: 'JENTECH PRECISION INDUSTRIAL CO., LTD' },
  { code: '4925', name: '智微科技', englishName: 'FARADAY TECH (JMicron Technology Corp.)' },
  { code: '4966', name: '谱瑞科技', englishName: 'PARADE TECH (Parade Technologies, Ltd.)' },
  { code: '5269', name: '祥硕科技', englishName: 'ASMEDIA TECH (ASMedia Technology Inc.)' },
  { code: '5274', name: '信骅科技', englishName: 'ASPEED TECH (ASPEED Technology Inc.)' },
  { code: '5347', name: '世界先进', englishName: 'VANGUARD INTL (Vanguard Int\'l Semiconductor)' },
  { code: '5439', name: '高技企业', englishName: 'Kao Gih Technology Co., Ltd.' },
  { code: '6274', name: '台燿科技', englishName: 'TAIWAN UNION TECHNOLOGY CORPORATION' },
  { code: '6488', name: '环球晶圆', englishName: 'GLOBAL WAFERS' },
  { code: '6669', name: '纬颖', englishName: 'Wiwynn Corporation' },
  { code: '6805', name: '富世达', englishName: 'FOSITEK CORP.' },
  { code: '8299', name: '群联电子', englishName: 'PHISON ELEC (Phison Electronics Corp.)' },
  { code: '8416', name: '实威国际', englishName: 'SCIENTECH' },
  { code: '8996', name: '高力', englishName: 'KAORI HEAT TREATMENT CO., LTD' },
];

export const cnStocks: Stock[] = [
    { code: '002463', name: '沪士电', englishName: 'WUS Printed Circuit (Kunshan) Co.,Ltd.' },
    { code: '300308', name: '中际旭创', englishName: 'Zhongji Innolight Co.,Ltd.' },
    { code: '300476', name: '胜宏', englishName: 'Victory Giant Technology (HuiZhou)Co.,Ltd.' },
    { code: '300502', name: '新易盛', englishName: 'Eoptolink Technology Inc.,Ltd.' },
    { code: '601138', name: '富士康工业互联网', englishName: 'Foxconn Industrial Internet Co., Ltd.' },
];

export const usStocks: Stock[] = [
    { code: 'SNOW', name: 'Snowflake', englishName: 'Snowflake Inc.' },
    { code: 'GOOG', name: 'Alphabet', englishName: 'Alphabet Inc.' },
    { code: 'NFLX', name: 'Netflix', englishName: 'Netflix, Inc.' },
    { code: 'COHR', name: '相干公司（Coherent）', englishName: 'Coherent Corp.' },
    { code: 'AVGO', name: '博通', englishName: 'Broadcom Inc.' },
    { code: 'NVDA', name: '英伟达', englishName: 'NVIDIA Corporation' },
    { code: 'CRDO', name: 'Credo科技', englishName: 'Credo Technology Group Holding Ltd.' },
    { code: 'ALAB', name: 'Astera Labs', englishName: 'Astera Labs, Inc.' },
    { code: 'TTMI', name: '鼎通（TTM科技）', englishName: 'TTM Technologies, Inc.' },
]; 